// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	Order          *order
	Poster         *poster
	Transaction    *transaction
	User           *user
	UserBalance    *userBalance
	UserCredential *userCredential
	VerifyCode     *verifyCode
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Order = &Q.Order
	Poster = &Q.Poster
	Transaction = &Q.Transaction
	User = &Q.User
	UserBalance = &Q.UserBalance
	UserCredential = &Q.UserCredential
	VerifyCode = &Q.VerifyCode
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Order:          newOrder(db, opts...),
		Poster:         newPoster(db, opts...),
		Transaction:    newTransaction(db, opts...),
		User:           newUser(db, opts...),
		UserBalance:    newUserBalance(db, opts...),
		UserCredential: newUserCredential(db, opts...),
		VerifyCode:     newVerifyCode(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Order          order
	Poster         poster
	Transaction    transaction
	User           user
	UserBalance    userBalance
	UserCredential userCredential
	VerifyCode     verifyCode
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Order:          q.Order.clone(db),
		Poster:         q.Poster.clone(db),
		Transaction:    q.Transaction.clone(db),
		User:           q.User.clone(db),
		UserBalance:    q.UserBalance.clone(db),
		UserCredential: q.UserCredential.clone(db),
		VerifyCode:     q.VerifyCode.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Order:          q.Order.replaceDB(db),
		Poster:         q.Poster.replaceDB(db),
		Transaction:    q.Transaction.replaceDB(db),
		User:           q.User.replaceDB(db),
		UserBalance:    q.UserBalance.replaceDB(db),
		UserCredential: q.UserCredential.replaceDB(db),
		VerifyCode:     q.VerifyCode.replaceDB(db),
	}
}

type queryCtx struct {
	Order          IOrderDo
	Poster         IPosterDo
	Transaction    ITransactionDo
	User           IUserDo
	UserBalance    IUserBalanceDo
	UserCredential IUserCredentialDo
	VerifyCode     IVerifyCodeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Order:          q.Order.WithContext(ctx),
		Poster:         q.Poster.WithContext(ctx),
		Transaction:    q.Transaction.WithContext(ctx),
		User:           q.User.WithContext(ctx),
		UserBalance:    q.UserBalance.WithContext(ctx),
		UserCredential: q.UserCredential.WithContext(ctx),
		VerifyCode:     q.VerifyCode.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
