// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zhifeiji/auradraw/backend/models"
)

func newPoster(db *gorm.DB, opts ...gen.DOOption) poster {
	_poster := poster{}

	_poster.posterDo.UseDB(db, opts...)
	_poster.posterDo.UseModel(&models.Poster{})

	tableName := _poster.posterDo.TableName()
	_poster.ALL = field.NewAsterisk(tableName)
	_poster.ID = field.NewInt64(tableName, "id")
	_poster.UserID = field.NewInt64(tableName, "user_id")
	_poster.Prompt = field.NewString(tableName, "prompt")
	_poster.Status = field.NewString(tableName, "status")
	_poster.ImageURL = field.NewString(tableName, "image_url")
	_poster.Cost = field.NewInt64(tableName, "cost")
	_poster.CreatedAt = field.NewTime(tableName, "created_at")
	_poster.UpdatedAt = field.NewTime(tableName, "updated_at")

	_poster.fillFieldMap()

	return _poster
}

// poster Poster Generation Records
type poster struct {
	posterDo

	ALL       field.Asterisk
	ID        field.Int64  // Primary Key
	UserID    field.Int64  // FK -> user.id
	Prompt    field.String // User Input Parameters (Prompt, Style, etc.)
	Status    field.String // Status: pending, processing, completed, failed
	ImageURL  field.String // Result Image URL
	Cost      field.Int64  // Credits Consumed
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p poster) Table(newTableName string) *poster {
	p.posterDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p poster) As(alias string) *poster {
	p.posterDo.DO = *(p.posterDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *poster) updateTableName(table string) *poster {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.UserID = field.NewInt64(table, "user_id")
	p.Prompt = field.NewString(table, "prompt")
	p.Status = field.NewString(table, "status")
	p.ImageURL = field.NewString(table, "image_url")
	p.Cost = field.NewInt64(table, "cost")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *poster) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *poster) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["prompt"] = p.Prompt
	p.fieldMap["status"] = p.Status
	p.fieldMap["image_url"] = p.ImageURL
	p.fieldMap["cost"] = p.Cost
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p poster) clone(db *gorm.DB) poster {
	p.posterDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p poster) replaceDB(db *gorm.DB) poster {
	p.posterDo.ReplaceDB(db)
	return p
}

type posterDo struct{ gen.DO }

type IPosterDo interface {
	gen.SubQuery
	Debug() IPosterDo
	WithContext(ctx context.Context) IPosterDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPosterDo
	WriteDB() IPosterDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPosterDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPosterDo
	Not(conds ...gen.Condition) IPosterDo
	Or(conds ...gen.Condition) IPosterDo
	Select(conds ...field.Expr) IPosterDo
	Where(conds ...gen.Condition) IPosterDo
	Order(conds ...field.Expr) IPosterDo
	Distinct(cols ...field.Expr) IPosterDo
	Omit(cols ...field.Expr) IPosterDo
	Join(table schema.Tabler, on ...field.Expr) IPosterDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPosterDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPosterDo
	Group(cols ...field.Expr) IPosterDo
	Having(conds ...gen.Condition) IPosterDo
	Limit(limit int) IPosterDo
	Offset(offset int) IPosterDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPosterDo
	Unscoped() IPosterDo
	Create(values ...*models.Poster) error
	CreateInBatches(values []*models.Poster, batchSize int) error
	Save(values ...*models.Poster) error
	First() (*models.Poster, error)
	Take() (*models.Poster, error)
	Last() (*models.Poster, error)
	Find() ([]*models.Poster, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Poster, err error)
	FindInBatches(result *[]*models.Poster, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Poster) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPosterDo
	Assign(attrs ...field.AssignExpr) IPosterDo
	Joins(fields ...field.RelationField) IPosterDo
	Preload(fields ...field.RelationField) IPosterDo
	FirstOrInit() (*models.Poster, error)
	FirstOrCreate() (*models.Poster, error)
	FindByPage(offset int, limit int) (result []*models.Poster, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPosterDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p posterDo) Debug() IPosterDo {
	return p.withDO(p.DO.Debug())
}

func (p posterDo) WithContext(ctx context.Context) IPosterDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p posterDo) ReadDB() IPosterDo {
	return p.Clauses(dbresolver.Read)
}

func (p posterDo) WriteDB() IPosterDo {
	return p.Clauses(dbresolver.Write)
}

func (p posterDo) Session(config *gorm.Session) IPosterDo {
	return p.withDO(p.DO.Session(config))
}

func (p posterDo) Clauses(conds ...clause.Expression) IPosterDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p posterDo) Returning(value interface{}, columns ...string) IPosterDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p posterDo) Not(conds ...gen.Condition) IPosterDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p posterDo) Or(conds ...gen.Condition) IPosterDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p posterDo) Select(conds ...field.Expr) IPosterDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p posterDo) Where(conds ...gen.Condition) IPosterDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p posterDo) Order(conds ...field.Expr) IPosterDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p posterDo) Distinct(cols ...field.Expr) IPosterDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p posterDo) Omit(cols ...field.Expr) IPosterDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p posterDo) Join(table schema.Tabler, on ...field.Expr) IPosterDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p posterDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPosterDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p posterDo) RightJoin(table schema.Tabler, on ...field.Expr) IPosterDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p posterDo) Group(cols ...field.Expr) IPosterDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p posterDo) Having(conds ...gen.Condition) IPosterDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p posterDo) Limit(limit int) IPosterDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p posterDo) Offset(offset int) IPosterDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p posterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPosterDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p posterDo) Unscoped() IPosterDo {
	return p.withDO(p.DO.Unscoped())
}

func (p posterDo) Create(values ...*models.Poster) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p posterDo) CreateInBatches(values []*models.Poster, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p posterDo) Save(values ...*models.Poster) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p posterDo) First() (*models.Poster, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Poster), nil
	}
}

func (p posterDo) Take() (*models.Poster, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Poster), nil
	}
}

func (p posterDo) Last() (*models.Poster, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Poster), nil
	}
}

func (p posterDo) Find() ([]*models.Poster, error) {
	result, err := p.DO.Find()
	return result.([]*models.Poster), err
}

func (p posterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Poster, err error) {
	buf := make([]*models.Poster, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p posterDo) FindInBatches(result *[]*models.Poster, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p posterDo) Attrs(attrs ...field.AssignExpr) IPosterDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p posterDo) Assign(attrs ...field.AssignExpr) IPosterDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p posterDo) Joins(fields ...field.RelationField) IPosterDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p posterDo) Preload(fields ...field.RelationField) IPosterDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p posterDo) FirstOrInit() (*models.Poster, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Poster), nil
	}
}

func (p posterDo) FirstOrCreate() (*models.Poster, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Poster), nil
	}
}

func (p posterDo) FindByPage(offset int, limit int) (result []*models.Poster, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p posterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p posterDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p posterDo) Delete(models ...*models.Poster) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *posterDo) withDO(do gen.Dao) *posterDo {
	p.DO = *do.(*gen.DO)
	return p
}
