// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrder = "order"

// Order Recharge Orders
type Order struct {
	ID            int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"`                         // Primary Key
	OrderID       string     `gorm:"column:order_id;not null;comment:Business Order ID" json:"order_id"`                            // Business Order ID
	UserID        int64      `gorm:"column:user_id;not null;comment:FK -> user.id" json:"user_id"`                                  // FK -> user.id
	Amount        int64      `gorm:"column:amount;not null;comment:Payment Amount (CNY Cents)" json:"amount"`                       // Payment Amount (CNY Cents)
	Credits       int64      `gorm:"column:credits;not null;comment:Credits to Add" json:"credits"`                                 // Credits to Add
	PaymentMethod string     `gorm:"column:payment_method;not null;comment:alipay, wechat" json:"payment_method"`                   // alipay, wechat
	PayURL        string     `gorm:"column:pay_url;not null;comment:支付链接" json:"pay_url"`                                           // 支付链接
	ProductInfo   string     `gorm:"column:product_info;not null;comment:下单时商品信息" json:"product_info"`                              // 下单时商品信息
	Status        string     `gorm:"column:status;not null;default:pending;comment:Status: pending, paid, cancelled" json:"status"` // Status: pending, paid, cancelled
	CreatedAt     time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	ExpireAt      time.Time  `gorm:"column:expire_at;not null;comment:订单过期时间" json:"expire_at"` // 订单过期时间
	PaidAt        *time.Time `gorm:"column:paid_at;comment:支付时间" json:"paid_at"`                // 支付时间
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
