// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePoster = "poster"

// Poster Poster Generation Records
type Poster struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"`                                       // Primary Key
	UserID    int64     `gorm:"column:user_id;not null;comment:FK -> user.id" json:"user_id"`                                                // FK -> user.id
	Prompt    string    `gorm:"column:prompt;not null;comment:User Input Parameters (Prompt, Style, etc.)" json:"prompt"`                    // User Input Parameters (Prompt, Style, etc.)
	Status    string    `gorm:"column:status;not null;default:pending;comment:Status: pending, processing, completed, failed" json:"status"` // Status: pending, processing, completed, failed
	ImageURL  string    `gorm:"column:image_url;comment:Result Image URL" json:"image_url"`                                                  // Result Image URL
	Cost      int64     `gorm:"column:cost;not null;comment:Credits Consumed" json:"cost"`                                                   // Credits Consumed
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Poster's table name
func (*Poster) TableName() string {
	return TableNamePoster
}
