// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTransaction = "transaction"

// Transaction Credit Transaction History
type Transaction struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"`                       // Primary Key
	UserID      int64     `gorm:"column:user_id;not null;comment:FK -> user.id" json:"user_id"`                                // FK -> user.id
	Type        string    `gorm:"column:type;not null;comment:recharge, consume" json:"type"`                                  // recharge, consume
	Amount      int64     `gorm:"column:amount;not null;comment:Credit Change Amount (+/-)" json:"amount"`                     // Credit Change Amount (+/-)
	ReferenceID int64     `gorm:"column:reference_id;not null;comment:Related ID (Order ID or Poster ID)" json:"reference_id"` // Related ID (Order ID or Poster ID)
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
