// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserCredential = "user_credential"

// UserCredential User Credentials
type UserCredential struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"`         // Primary Key
	UserID       int64     `gorm:"column:user_id;not null;comment:FK -> user.id" json:"user_id"`                  // FK -> user.id
	PasswordHash string    `gorm:"column:password_hash;not null;comment:Encrypted Password" json:"password_hash"` // Encrypted Password
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserCredential's table name
func (*UserCredential) TableName() string {
	return TableNameUserCredential
}
