// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserBalance = "user_balance"

// UserBalance User Wallet Balance
type UserBalance struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"` // Primary Key
	UserID    int64     `gorm:"column:user_id;not null;comment:FK -> user.id" json:"user_id"`          // FK -> user.id
	Balance   int64     `gorm:"column:balance;not null;comment:Remaining Credits" json:"balance"`      // Remaining Credits
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserBalance's table name
func (*UserBalance) TableName() string {
	return TableNameUserBalance
}
