// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "user"

// User User Basic Info
type User struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"` // Primary Key
	Email     string    `gorm:"column:email;not null" json:"email"`
	Provider  string    `gorm:"column:provider;not null;default:email" json:"provider"`
	Status    string    `gorm:"column:status;not null;default:enabled" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
