// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameVerifyCode = "verify_code"

// VerifyCode Verify Code
type VerifyCode struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"` // Primary Key
	Email     string     `gorm:"column:email;not null;comment:User Email" json:"email"`                 // User Email
	Code      string     `gorm:"column:code;not null;comment:Verify Code" json:"code"`                  // Verify Code
	Type      string     `gorm:"column:type;not null;default:"";comment:verify code tyep" json:"type"`  // verify code tyep
	Token     string     `gorm:"column:token;not null;comment:Verify Token" json:"token"`               // Verify Token
	CreatedAt time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	ExpiredAt time.Time  `gorm:"column:expired_at;not null;comment:Expire Time" json:"expired_at"` // Expire Time
	UsedAt    *time.Time `gorm:"column:used_at;comment:Used Time" json:"used_at"`                  // Used Time
}

// TableName VerifyCode's table name
func (*VerifyCode) TableName() string {
	return TableNameVerifyCode
}
